# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)

 # User.create!(admin: true, name: "admin", email: "nutrimedi@nutrimedi.com.br", password: "nutrimedi2021", password_confirmation: "nutrimedi2021")
   
Product.create!(name: 'ABANOX 500 ML')
Product.create!(name: 'ACTIVO 25G')
Product.create!(name: 'AGULHA CANHÃO REDONDO  25X15')
Product.create!(name: 'AGULHA CANHÃO REDONDO 10X08')
Product.create!(name: 'AGULHA CANHÃO REDONDO 10X10')
Product.create!(name: 'AGULHA CANHÃO REDONDO 15X10')
Product.create!(name: 'AGULHA CANHÃO REDONDO 25X12')
Product.create!(name: 'AGULHA CANHÃO REDONDO 30X12')
Product.create!(name: 'AGULHA CANHÃO REDONDO 30X15')
Product.create!(name: 'AGULHA CANHÃO REDONDO 40X12')
Product.create!(name: 'ANABOLIC 200 ML')
Product.create!(name: 'ANABOLIC 50 ML')
Product.create!(name: 'ANABOLIC 500 ML')
Product.create!(name: 'ANTITOXICO INJ. 100 ML')
Product.create!(name: 'BARATICIDA 10 G (INDOXACARB GEL B)')
Product.create!(name: 'BASTÃO MARCADOR AZUL')
Product.create!(name: 'BASTÃO MARCADOR VERMELHO')
Product.create!(name: 'BIATACK 1 LITRO')
Product.create!(name: 'BIATACK 5 LITRO')
Product.create!(name: 'BIOBOND 25KG')
Product.create!(name: 'BIOBOND AZ 20KG')
Product.create!(name: 'BIOBOND MAX PRÓ - 25KG')
Product.create!(name: 'CATOL 100ML')
Product.create!(name: 'CATOL 20ML')
Product.create!(name: 'CATOL 250 ML')
Product.create!(name: 'COELHO  CP PEL 25KG')
Product.create!(name: 'COELHO CP PEL - fardo 25kg')
Product.create!(name: 'COMEDOURO LEITÃO')
Product.create!(name: 'CONCENTRADO OPTIFARM - 20 KG')
Product.create!(name: 'CONCENTRADO POWER 3 20KG')
Product.create!(name: 'CONCENTRADO POWER 4 20KG')
Product.create!(name: 'CONCENTRADO PROGRESS 3')
Product.create!(name: 'CONCENTRADO PROGRESS 4')
Product.create!(name: 'COURO LIMPO 1 LITRO')
Product.create!(name: 'COURO LIMPO 100 ML')
Product.create!(name: 'COURO LIMPO 25 ML')
Product.create!(name: 'COURO LIMPO 250 ML')
Product.create!(name: 'COURO LIMPO POUR ON 1 LITRO')
Product.create!(name: 'COURO LIMPO POUR ON 5 LITRO')
Product.create!(name: 'COURO LIMPO PRATA V18 200ML')
Product.create!(name: 'COURO LIMPO PRATA V18 500ML')
Product.create!(name: 'DICLOFENACO JÁ 100 ML')
Product.create!(name: 'DICLOFENACO JÁ 50 ML')
Product.create!(name: 'DIPIRONA 50%')
Product.create!(name: 'ENRO FLEC INJ 500 ML')
Product.create!(name: 'FARMADOX 50 200G')
Product.create!(name: 'FARMADOX 50% 25KG')
Product.create!(name: 'FARMAXILIN 50% 20KG')
Product.create!(name: 'FLORFENIMAX 25KG')
Product.create!(name: 'FLUNIXIN INJETÁVEL 100ML')
Product.create!(name: 'FLUNIXIN INJETÁVEL 50ML')
Product.create!(name: 'FORMICIDA 10G (INDOXCARB GEL F)')
Product.create!(name: 'FORTICILINA 4G')
Product.create!(name: 'FUSION 1 LITRO')
Product.create!(name: 'FUSION 5 LITRO')
Product.create!(name: 'GOLDMAC 500 ML')
Product.create!(name: 'GOLDMEC 50 ML')
Product.create!(name: 'GOLDMEC 500 ML')
Product.create!(name: 'HORSENOX 9G')
Product.create!(name: 'INTRASEC')
Product.create!(name: 'IVERMECTINA PREMIX 0,6% 5KG')
Product.create!(name: 'IVONOX 200 ML')
Product.create!(name: 'IVONOX 50 ML')
Product.create!(name: 'IVONOX 500 ML')
Product.create!(name: 'KALIBER INICIAL PELLET 40KG')
Product.create!(name: 'KALIBER LAC NOVILHAS 30 KG')
Product.create!(name: 'KALIBER LAC SUPREME')
Product.create!(name: 'KALIBER MILK IMPORTADO 25 KG')
Product.create!(name: 'KALIBER NOVILHAS 17 PELLET 40KG')
Product.create!(name: 'KINETOMAX 100ML')
Product.create!(name: 'KINETOMAX 50ML')
Product.create!(name: 'LACTUS POUR ON 1% 1 LITRO')
Product.create!(name: 'LEVAMISOL 1 LITRO')
Product.create!(name: 'LEVAMISOL 250 ML')
Product.create!(name: 'LEVAMISOL 500 ML')
Product.create!(name: 'MASTERFLY 1 LITRO')
Product.create!(name: 'MASTERFLY 20 ML')
Product.create!(name: 'MILLEMIUM 250 ML 50DOSES')
Product.create!(name: 'MILLEMIUM 50 ML 10DOSES')
Product.create!(name: 'MITRANOX 1LITRO')
Product.create!(name: 'MITRANOX 200 ML')
Product.create!(name: 'MITRANOX 40 ML')
Product.create!(name: 'MS RODETOX GRÃOS (RATICIDA)')
Product.create!(name: 'MUB BEEF ACCELERATOR 50KG')
Product.create!(name: 'MUB BEEF COMPACT 50 KG')
Product.create!(name: 'MUB BEEF ENERGY 50 KG')
Product.create!(name: 'MUB BEEF FERTILE 50 KG')
Product.create!(name: 'MUB BEEF STARTER 50 KG')
Product.create!(name: 'MUB BEEF SUPORT 50 KG')
Product.create!(name: 'MUB IMPULSE 50 KG')
Product.create!(name: 'MUB MILK 50 KG')
Product.create!(name: 'MUB MILK CARE 50 KG')
Product.create!(name: 'MUB PERFORM 50KG')
Product.create!(name: 'NUC. POWER CRESCIMENTO PRECISÃO 20KG')
Product.create!(name: 'NUC. POWER GESTAÇÃO PRECISÃO')
Product.create!(name: 'NUC. POWER INICIAL  PRIME - 25KG')
Product.create!(name: 'NUC. POWER INICIAL PRECISÃO - 20KG')
Product.create!(name: 'NUC. POWER INICIAL PRECISÃO 5%')
Product.create!(name: 'NUC. POWER LACTAÇÃO BND 20 KG')
Product.create!(name: 'NUC. POWER LACTAÇÃO EQUILIBRIO 30KG')
Product.create!(name: 'NUC. POWER LACTAÇÃO PRECISÃO')
Product.create!(name: 'NUC. POWER MARRÃ PRECISÃO')
Product.create!(name: 'NUC. PROGRESS CRESCIMENTO EQUILIBRIO 15 KG')
Product.create!(name: 'NUC. PROGRESS CRESCIMENTO EQUILIBRIO 30 KG')
Product.create!(name: 'NUC. PROGRESS GESTAÇÃO EQUILIBRIO 15KG')
Product.create!(name: 'NUC. PROGRESS GESTAÇÃO EQUILIBRIO 30KG')
Product.create!(name: 'NUC. PROGRESS INICIAL EQUILIBRIO 15 KG')
Product.create!(name: 'NUC. PROGRESS INICIAL EQUILIBRIO 30 KG')
Product.create!(name: 'NUC. PROGRESS REPRODUÇÃO EQUILIBRIO 15 kg')
Product.create!(name: 'NUC. PROGRESS REPRODUÇÃO EQUILIBRIO 30 kg')
Product.create!(name: 'NUC. PROGRESS TERMINAÇÃO EQUILIBRIO 15 KG')
Product.create!(name: 'NUC. PROGRESS TERMINAÇÃO EQUILIBRIO 30 KG')
Product.create!(name: 'NUCLEO POWER TERMINAÇÃO PRECISÃO - 20 kg')
Product.create!(name: 'NUTRIFER 20 FERRO IBASA')
Product.create!(name: 'PEGASUS TRIO 9G')
Product.create!(name: 'PIROSEG 30ML')
Product.create!(name: 'PÓ SECANTE GOLDUST')
Product.create!(name: 'POWER  FÓS VITA EQUI - 10 KG')
Product.create!(name: 'POWER ARROBA 10 ADITIVADO')
Product.create!(name: 'POWER ARROBA 20 ADITIVADO')
Product.create!(name: 'POWER BEEF 1000 M 40 KG')
Product.create!(name: 'POWER BEEF 250 M')
Product.create!(name: 'POWER BUFFER')
Product.create!(name: 'POWER CAPRINOS 40')
Product.create!(name: 'POWER CREEP 20 ADT')
Product.create!(name: 'POWER ENERGY PLUS 20KG')
Product.create!(name: 'POWER FOS 120')
Product.create!(name: 'POWER FÓS 160')
Product.create!(name: 'POWER FÓS CRESCIMENTO 30KG')
Product.create!(name: 'POWER FÓS CRIA')
Product.create!(name: 'POWER FÓS CRIA ADT')
Product.create!(name: 'POWER FÓS ENGORDA 30KG')
Product.create!(name: 'POWER FÓS LACTAÇÃO ADE')
Product.create!(name: 'POWER FÓS OVINOS - 15KG')
Product.create!(name: 'POWER FÓS RECRIA 30 KG')
Product.create!(name: 'POWER FÓS REPRODUÇÃO ')
Product.create!(name: 'POWER LAC 30')
Product.create!(name: 'POWER LAC 30M')
Product.create!(name: 'POWER LAC 30MB')
Product.create!(name: 'POWER LAC 40MB')
Product.create!(name: 'POWER LAC 50 ABSOLUTE TP')
Product.create!(name: 'POWER LAC PRÉ PARTO')
Product.create!(name: 'POWER LAC PRÉ PARTO IONIC')
Product.create!(name: 'POWER MILK')
Product.create!(name: 'POWER MILK PLUS 25 KG')
Product.create!(name: 'POWER NUCLEO FRANGOS ENGORDA 4')
Product.create!(name: 'POWER NUCLEO FRANGOS INICIAL')
Product.create!(name: 'POWER NUCLEO FRANGOS POSTURA 4')
Product.create!(name: 'POWER PESO 30')
Product.create!(name: 'POWER PESO 30 ADITIVADO')
Product.create!(name: 'POWER PESO 45 ADITIVADO')
Product.create!(name: 'PRELACTO AMARELO PELET (PRÉ-PARTO)')
Product.create!(name: 'PRO BEZERRO PLUS')
Product.create!(name: 'PRO HORSE + PLUS')
Product.create!(name: 'PRO HORSE 34G')
Product.create!(name: 'PRO HORSE POTROS')
Product.create!(name: 'PRO MILK')
Product.create!(name: 'PRO RUMEN')
Product.create!(name: 'PRO-VAC CIRCOMASTER 100 ML 100DS')
Product.create!(name: 'RATICIDA (BRODIFACOUM DISPLAY)')
Product.create!(name: 'RATICIDA 20G (BRODIFACOUM- R GRAN)')
Product.create!(name: 'RATICIDA BLOCO 500G (BLOCO PARAFINADO)')
Product.create!(name: 'RATICIDA PO 1KG (PO DE CONTATO)')
Product.create!(name: 'RICOBEN 250 ML')
Product.create!(name: 'RICOBEN 500 ML')
Product.create!(name: 'SANIMAX PLUS - 1L')
Product.create!(name: 'SAU-ABORT 50ML 25 DOSES')
Product.create!(name: 'SAU-RAP 50ML 25 DOSES')
Product.create!(name: 'SELAMAST 4G')
Product.create!(name: 'SEMENTE  DE AZEVEM NIBBIO 25KG')
Product.create!(name: 'SEMENTE DE AZEVEM CERONTE 25KG')
Product.create!(name: 'SEMENTE DE BRACHIARIA BRIZANTHIA CV MARANDU')
Product.create!(name: 'SEMENTE DE BRACHIARIA PIATÃ')
Product.create!(name: 'SEMENTE DE BRACHIARIA RUZIZIENZIS')
Product.create!(name: 'SEMENTE DE BRACHIARIA XARAÉS')
Product.create!(name: 'SEMENTE DE CROTALARIA SPECTABILIS - 25 KG')
Product.create!(name: 'SEMENTE DE MILHETO ADR 300 - 25 KG')
Product.create!(name: 'SEMENTE DE MILHETO ADR 500 - 25 KG')
Product.create!(name: 'SEMENTE DE MILHETO ADRF 6010 - 15 KG')
Product.create!(name: 'SEMENTE DE TREVO ALEXANDRINO 10KG')
Product.create!(name: 'SERKEL GASTRO 50ML 25 DOSES')
Product.create!(name: 'SERKEL GASTRO RV 50ML')
Product.create!(name: 'SERKEL PNEUMO 100ML 50 DOSES')
Product.create!(name: 'SINCROCIO 20 ML')
Product.create!(name: 'SOLUCEF PPU 100 ML')
Product.create!(name: 'SPRAY MARCADOR AZUL')
Product.create!(name: 'SPRAY MARCADOR VERMELHO')
Product.create!(name: 'SUIVEN 50 ML')
Product.create!(name: 'SUPER CALCIO 200 ML')
Product.create!(name: 'SUPER CALCIO 500 ML')
Product.create!(name: 'SUPRA PEN 50 ML')
Product.create!(name: 'SUPREMO 3,50 1000ML')
Product.create!(name: 'SUPREMO 3,50 500ML')
Product.create!(name: 'SUPREMO 3,50 50ML')
Product.create!(name: 'TERRAMAX 100 ML')
Product.create!(name: 'TERRAMAX 50ML')
Product.create!(name: 'TIAMULINA 80% 15KG')
Product.create!(name: 'TOPMAST 10G')
Product.create!(name: 'URÉIA PECUARIA 25KG')
Product.create!(name: 'ZUUM 24x25G')